name: Refresh GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Curl a dummy request to keep stats fresh
        run: |
          curl -s https://github-readme-stats.vercel.app/api?username=PrinceRaut01 > /dev/null
